CREATE TABLE [dbo].[DimDB]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[Name] [nvarchar] (50) COLLATE Persian_100_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimDB] ADD CONSTRAINT [PK_DimDB] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimDB] ADD CONSTRAINT [IX_DimDB_Name] UNIQUE NONCLUSTERED  ([Name]) ON [PRIMARY]
GO
