IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'DESKTOP-Q8FI99Q\Farshad')
CREATE LOGIN [DESKTOP-Q8FI99Q\Farshad] FROM WINDOWS
GO
CREATE USER [DESKTOP-Q8FI99Q\Farshad] FOR LOGIN [DESKTOP-Q8FI99Q\Farshad]
GO
